/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    CardInfoOrder: typeof import('./src/components/Orders/CardInfoOrder.vue')['default']
    ListOrders: typeof import('./src/components/Orders/ListOrders.vue')['default']
    OrderItemList: typeof import('./src/components/Orders/OrderItemList.vue')['default']
    ProductItemCard: typeof import('./src/components/ProductItemCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
