/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/login': RouteRecordInfo<'/account/login', '/account/login', Record<never, never>, Record<never, never>>,
    '/account/me': RouteRecordInfo<'/account/me', '/account/me', Record<never, never>, Record<never, never>>,
    '/account/signup': RouteRecordInfo<'/account/signup', '/account/signup', Record<never, never>, Record<never, never>>,
    '/orders/[id]/congratulations': RouteRecordInfo<'/orders/[id]/congratulations', '/orders/:id/congratulations', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/finish': RouteRecordInfo<'/orders/[id]/finish', '/orders/:id/finish', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/product/[id]': RouteRecordInfo<'/product/[id]', '/product/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
